import {
  Target,
  Code,
  CheckCircle2,
  Droplets,
  BookOpen,
  Camera,
  Briefcase,
} from "lucide-react";

export const taskDefinitions = [
  {
    id: "workout1",
    label: "Morning Workout",
    sublabel: "45+ min",
    icon: Target,
    color: "text-red-400",
    bg: "bg-red-500/10",
  },
  {
    id: "workout2",
    label: "Evening Coding",
    sublabel: "45+ min",
    icon: Code,
    color: "text-blue-400",
    bg: "bg-blue-500/10",
  },
  {
    id: "diet",
    label: "Clean Diet",
    sublabel: "No cheat meals",
    icon: CheckCircle2,
    color: "text-green-400",
    bg: "bg-green-500/10",
  },
  {
    id: "water",
    label: "Gallon of Water",
    sublabel: "3.8L daily",
    icon: Droplets,
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
  },
  {
    id: "reading",
    label: "Tech Reading",
    sublabel: "10+ pages",
    icon: BookOpen,
    color: "text-purple-400",
    bg: "bg-purple-500/10",
  },
  {
    id: "photo",
    label: "Progress Doc",
    sublabel: "Daily photo",
    icon: Camera,
    color: "text-yellow-400",
    bg: "bg-yellow-500/10",
  },
  {
    id: "coding",
    label: "GitHub Commit",
    sublabel: "Daily code",
    icon: Code,
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
  },
  {
    id: "jobApps",
    label: "Job Applications",
    sublabel: "2-3 apps",
    icon: Briefcase,
    color: "text-orange-400",
    bg: "bg-orange-500/10",
  },
  {
    id: "interview",
    label: "Interview Prep",
    sublabel: "Coding practice",
    icon: Target,
    color: "text-pink-400",
    bg: "bg-pink-500/10",
  },
];

export const initialDailyTasks = {
  workout1: false,
  workout2: false,
  diet: false,
  water: false,
  reading: false,
  photo: false,
  coding: false,
  jobApps: false,
  interview: false,
};
